name: Lint shell scripts

on: push

jobs:
  lint:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.0.0
        with:
          scandir: 'store/.git_template/hooks'
